version: '3.1'
volumes:
  pg_timeweb:
services:
  pg_db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=timeweb
      - POSTGRES_USER=timeweb
      - POSTGRES_DB=timeweb
    ports:
      - 5434:5432